### PR TITLE
Reprocess haxelib git and mercurial dependencies support to adapt under haxelib.json format

### PR DESCRIPTION
**Pull request by romanmikhailov**
Warning:
haxelib.json doesn't support hg format and "sub directory" and "version" for git.
For mercurial support: https://github.com/HaxeFoundation/haxelib/pull/367

And need think if we need support sub directories and versions.
@eliasku Please advice.

### CODE REVIEW

**Comment by eliasku** [comment]
@romanmikhailov  We could remove haxelib Mercurial support at all to avoid confusion

**Comment by romanmikhailov** [comment]
@eliasku Probably we need remove subDir and version too?

**Comment by romanmikhailov** [comment]
After discussion with @eliasku we decide to left as is and add additional warning for hg and subDir and version for git usages. Pull request will be updated.

**Comment by romanmikhailov** [comment]
Added warnings when generating haxelib.json in case detecting mercurial or git (with sub directory or version) dependencies.

**Pull request merged**
